name: homepage
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./homepage-config:/app/config:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
      # HOMEPAGE_VAR_RADXA_PORTAINER_API_KEY: ${HOMEPAGE_VAR_RADXA_PORTAINER_API_KEY}
      HOMEPAGE_VAR_BITWARDEN_URL: ${HOMEPAGE_VAR_BITWARDEN_URL}
      HOMEPAGE_VAR_TAILSCALE_API_KEY: ${HOMEPAGE_VAR_TAILSCALE_API_KEY}
      HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ${HOMEPAGE_VAR_PROXMOX_TOKEN_ID}
      HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ${HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET}
      HOMEPAGE_VAR_PROXY_USERNAME: ${HOMEPAGE_VAR_PROXY_USERNAME}
      HOMEPAGE_VAR_PROXY_PASSWORD: ${HOMEPAGE_VAR_PROXY_PASSWORD}
      HOMEPAGE_VAR_PI_HOLE_API_KEY: ${HOMEPAGE_VAR_PI_HOLE_API_KEY}
      HOMEPAGE_VAR_DOCKHAND_USERNAME: ${HOMEPAGE_VAR_DOCKHAND_USERNAME}
      HOMEPAGE_VAR_DOCKHAND_PASSWORD: ${HOMEPAGE_VAR_DOCKHAND_PASSWORD}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - pve-local
networks:
  pve-local:
    external: true
