name: homepage

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./config/homepage:/app/config:rw
      - /mnt/sdcard:/mnt/sdcard:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: radxa-e25.tail539c2b.ts.net
      # see docs https://gethomepage.dev/installation/docker/#using-environment-secrets
      HOMEPAGE_VAR_RADXA_PORTAINER_API_KEY: ${HOMEPAGE_VAR_RADXA_PORTAINER_API_KEY}
      HOMEPAGE_VAR_BITWARDEN_URL: ${HOMEPAGE_VAR_BITWARDEN_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - homelab

networks:
  homelab:
    external: true
