name: uptime-kuma

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ${HOMELAB_VOLUMES}/uptime-kuma:/app/data:rw
    environment:
      - TZ=Europe/Brussels
    networks:
      - homelab

networks:
  homelab:
    external: true
