name: ntfy

services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    command: serve
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ${HOMELAB_VOLUMES}/ntfy:/data:rw
    ports:
      - 8085:80
    networks:
      - homelab

networks:
  homelab:
    external: true
