name: homepage

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - ./homepage:/app/config:rw
      - /mnt/sdcard:/mnt/sdcard:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: radxa-e25.tail539c2b.ts.net
      HOMEPAGE_VAR_PORTAINER_API_KEY: ${HOMEPAGE_VAR_PORTAINER_API_KEY}
    networks:
      - homelab

networks:
  homelab:
    external: true
