name: docs

services:
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: config/mkdocs/Dockerfile
    restart: unless-stopped
    ports:
      - "7300:80"
    networks:
      - homelab

networks:
  homelab:
    external: true
