name: portainer

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/sdcard/homelab-volumes/portainer:/data:rw
    networks:
      - homelab
      - portainer_bridge
    ports:
      # - 9000:9000
      - 9443:9443

volumes:
  portainer_data:
    external: true

networks:
  homelab:
    external: true
  portainer_bridge:
    driver: bridge
