name: openwebui

services:
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - 8090:8080
    environment:
      - TZ=Europe/Brussels
      - OLLAMA_BASE_URL=http://edge-ai-11.tail539c2b.ts.net:11434
    volumes:
      - ${HOMELAB_VOLUMES}/open-webui:/app/backend/data:rw
    networks:
      - homelab
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:8080/health || exit 1"]
      interval: 120s
      timeout: 5s
      retries: 3

networks:
  homelab:
    external: true
