site_name: Homelab Documentation
site_description: Documentation for my self-hosted homelab
site_author: Simon Stijnen
site_url: http://radxa-e25.tail539c2b.ts.net:7300/
repo_url: https://github.com/SimonStnn/homelab
copyright: Copyright 2025 Simon Stijnen

docs_dir: /app/docs

theme:
  name: material
  locale: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: yellow
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      accent: yellow
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: yellow
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - toc:
      permalink: true
  - attr_list

plugins:
  - search
