---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Radxa E25 - Homelab
description: Personal Homelab Dashboard
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
headerStyle: boxedWidgets
cardBlur: xs
showStats: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom